In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
# Importando la biblioteca pandas para manipulación y análisis de datos
import pandas as pd

# Importando NumPy para operaciones numéricas y manipulación de arreglos
import numpy as np

# Importando Seaborn para visualización de datos estadísticos (opcional, pero puede complementar a Plotly)
import seaborn as sns

# Importando Plotly Express para visualizaciones interactivas de alto nivel y fáciles de usar
import plotly.express as px

# Importando matplotlib.pyplot para crear gráficos y visualizaciones
import matplotlib.pyplot as plt

# Importando Plotly Graph Objects para un control más detallado sobre las visualizaciones
import plotly.graph_objects as go

# Importando itertools para generar combinaciones de columnas
import itertools

# Importando la función seasonal_decompose para la descomposición de series temporales
from statsmodels.tsa.seasonal import seasonal_decompose

In [3]:
cash_request=pd.read_csv('drive/MyDrive/ColabNotebooks/Business_Payments/extract - cash request - data analyst.csv')
fees=pd.read_csv('drive/MyDrive/ColabNotebooks/Business_Payments/extract - fees - data analyst - .csv')

In [21]:
# Realizar un inner join entre fees y cash_request
merged_df = fees.merge(
    cash_request,
    left_on='cash_request_id',
    right_on='id',
    how='inner'
)

# Guardar el resultado en un archivo CSV para análisis posterior
merged_df.to_csv('drive/MyDrive/ColabNotebooks/Business_Payments/inner_business_payments.csv', index=False)

print(f"Registros combinados: {len(merged_df)}")

Registros combinados: 21057

In [22]:
business_payments=pd.read_csv('drive/MyDrive/ColabNotebooks/inner_business_payments.csv')

In [23]:
business_payments.head()

,id_x,cash_request_id,type,status_x,category,total_amount,reason,created_at_x,updated_at_x,paid_at,...,moderated_at,deleted_account_id,reimbursement_date,cash_request_received_date,money_back_date,transfer_type,send_at,recovery_status,reco_creation,reco_last_update
0,6537,14941.0,instant_payment,rejected,NaN,5.0,Instant Payment Cash Request 14941,2020-09-07 10:47:27.42315+00,2020-10-13 14:25:09.396112+00,2020-12-17 14:50:07.47011+00,...,NaN,NaN,2020-10-01 22:00:00+00,NaN,2020-10-06 22:00:00+00,instant,2020-09-14 10:46:57.735172+00,pending,2020-10-11 22:52:52.274832+00,2020-12-20 22:40:42.556534+00
1,6961,11714.0,incident,accepted,rejected_direct_debit,5.0,rejected direct debit,2020-09-09 20:51:17.998653+00,2020-10-13 14:25:15.537063+00,2020-12-08 17:13:10.45908+00,...,2020-08-10 14:58:19.039748+00,NaN,2020-09-07 22:00:00+00,2020-08-12,2020-12-02 03:02:41.180953+00,instant,2020-08-17 13:15:54.290998+00,completed,2020-09-09 20:51:17.992852+00,2020-10-10 22:58:13.306027+00
2,16296,23371.0,instant_payment,accepted,NaN,5.0,Instant Payment Cash Request 23371,2020-10-23 10:10:58.352972+00,2020-10-23 10:10:58.352994+00,2020-11-04 19:34:37.43291+00,...,NaN,NaN,2020-11-04 22:00:00+00,2020-10-27,2020-11-04 19:34:37.399122+00,instant,2020-10-23 10:10:52.894637+00,NaN,NaN,NaN
3,20775,26772.0,instant_payment,accepted,NaN,5.0,Instant Payment Cash Request 26772,2020-10-31 15:46:53.643958+00,2020-10-31 15:46:53.643982+00,2020-11-19 05:09:22.500223+00,...,NaN,NaN,2020-11-11 23:51:00+00,2020-11-03,2020-11-17 23:00:00+00,instant,2020-10-31 15:46:46.846335+00,NaN,NaN,NaN
4,11242,19350.0,instant_payment,accepted,NaN,5.0,Instant Payment Cash Request 19350,2020-10-06 08:20:17.170432+00,2020-10-13 14:25:03.267983+00,2020-11-02 14:45:20.355598+00,...,2020-10-06 08:20:15.587318+00,19005.0,2020-10-30 11:00:00+00,2020-10-09,2020-11-02 14:45:20.315696+00,instant,2020-10-13 00:40:23.983346+00,completed,2020-10-24 22:43:13.278707+00,2020-11-02 14:45:20.333109+00

In [24]:
# Cargar los datos originales
cash_request=pd.read_csv('drive/MyDrive/ColabNotebooks/Business_Payments/extract - cash request - data analyst.csv')
fees=pd.read_csv('drive/MyDrive/ColabNotebooks/Business_Payments/extract - fees - data analyst - .csv')

# Convertir cash_request_id a enteros en fees
fees['cash_request_id'] = pd.to_numeric(fees['cash_request_id'], errors='coerce').dropna().astype(int)

# Realizar un outer join
merged_outer = fees.merge(
    cash_request,
    left_on='cash_request_id',
    right_on='id',
    how='outer',
    indicator=True
)

# Análisis de IDs ausentes
fees_only = merged_outer[merged_outer['_merge'] == 'left_only']
cash_request_only = merged_outer[merged_outer['_merge'] == 'right_only']

# Relación con cuentas eliminadas
deleted_related = cash_request_only[cash_request_only['deleted_account_id'].notnull()]

# Resultados de interés
fees_only_count = len(fees_only)
cash_request_only_count = len(cash_request_only)
deleted_related_count = len(deleted_related)

# Guardar el resultado del outer join para revisión
merged_outer.to_csv('drive/MyDrive/ColabNotebooks/Business_Payments/inner_business_payments.csv', index=False)

print(f"Registros solo en fees: {fees_only_count}")
print(f"Registros solo en cash_request: {cash_request_only_count}")
print(f"Registros relacionados con cuentas eliminadas: {deleted_related_count}")

Registros solo en fees: 4
Registros solo en cash_request: 11037
Registros relacionados con cuentas eliminadas: 1667

In [25]:
import pandas as pd

# Cargar los datos
cash_request=pd.read_csv('drive/MyDrive/ColabNotebooks/Business_Payments/extract - cash request - data analyst.csv')
fees=pd.read_csv('drive/MyDrive/ColabNotebooks/Business_Payments/extract - fees - data analyst - .csv')

# Limpiar y transformar la columna 'cash_request_id' en la tabla fees
fees['cash_request_id'] = fees['cash_request_id'].fillna(-1).astype(int)

# Realizar la unión (left join)
merged_df = fees.merge(cash_request, how='left', left_on='cash_request_id', right_on='id')

# Guardar el resultado en un nuevo archivo
merged_df.to_csv('drive/MyDrive/ColabNotebooks/Business_Payments/test_inner_business_payments.csv', index=False)

print("Unión completada y guardada en 'merged_fees_cash_request.csv'")

Unión completada y guardada en 'merged_fees_cash_request.csv'

In [26]:
test= pd.read_csv('drive/MyDrive/ColabNotebooks/Business_Payments/test_inner_business_payments.csv')

In [27]:
test.head()

,id_x,cash_request_id,type,status_x,category,total_amount,reason,created_at_x,updated_at_x,paid_at,...,moderated_at,deleted_account_id,reimbursement_date,cash_request_received_date,money_back_date,transfer_type,send_at,recovery_status,reco_creation,reco_last_update
0,6537,14941,instant_payment,rejected,NaN,5.0,Instant Payment Cash Request 14941,2020-09-07 10:47:27.42315+00,2020-10-13 14:25:09.396112+00,2020-12-17 14:50:07.47011+00,...,NaN,NaN,2020-10-01 22:00:00+00,NaN,2020-10-06 22:00:00+00,instant,2020-09-14 10:46:57.735172+00,pending,2020-10-11 22:52:52.274832+00,2020-12-20 22:40:42.556534+00
1,6961,11714,incident,accepted,rejected_direct_debit,5.0,rejected direct debit,2020-09-09 20:51:17.998653+00,2020-10-13 14:25:15.537063+00,2020-12-08 17:13:10.45908+00,...,2020-08-10 14:58:19.039748+00,NaN,2020-09-07 22:00:00+00,2020-08-12,2020-12-02 03:02:41.180953+00,instant,2020-08-17 13:15:54.290998+00,completed,2020-09-09 20:51:17.992852+00,2020-10-10 22:58:13.306027+00
2,16296,23371,instant_payment,accepted,NaN,5.0,Instant Payment Cash Request 23371,2020-10-23 10:10:58.352972+00,2020-10-23 10:10:58.352994+00,2020-11-04 19:34:37.43291+00,...,NaN,NaN,2020-11-04 22:00:00+00,2020-10-27,2020-11-04 19:34:37.399122+00,instant,2020-10-23 10:10:52.894637+00,NaN,NaN,NaN
3,20775,26772,instant_payment,accepted,NaN,5.0,Instant Payment Cash Request 26772,2020-10-31 15:46:53.643958+00,2020-10-31 15:46:53.643982+00,2020-11-19 05:09:22.500223+00,...,NaN,NaN,2020-11-11 23:51:00+00,2020-11-03,2020-11-17 23:00:00+00,instant,2020-10-31 15:46:46.846335+00,NaN,NaN,NaN
4,11242,19350,instant_payment,accepted,NaN,5.0,Instant Payment Cash Request 19350,2020-10-06 08:20:17.170432+00,2020-10-13 14:25:03.267983+00,2020-11-02 14:45:20.355598+00,...,2020-10-06 08:20:15.587318+00,19005.0,2020-10-30 11:00:00+00,2020-10-09,2020-11-02 14:45:20.315696+00,instant,2020-10-13 00:40:23.983346+00,completed,2020-10-24 22:43:13.278707+00,2020-11-02 14:45:20.333109+00